Metrics/LineLength:
  Enabled: false

Naming/VariableNumber:
  EnforcedStyle: snake_case

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/Send:
  Enabled: true

Style/SymbolArray:
  MinSize: 0

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'doc/**/*'
    - 'db/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
