---
- name: Refresh pacman cache
  pacman:
    name:
      - cups
      - cups-pdf
    update_cache: yes

- name: Copy ppd file
  copy:
    src: SCX-3400.ppd
    dest: /tmp/
    mode: 0640

- name: Add printers
  shell: lpadmin -p '{{ item.name }}' -v '{{ item.uri }}' -E -P '{{ item.ppd }}'
  with_items: '{{ host.print }}'

- name: Start cups service
  systemd:
    state: started
    name: org.cups.cupsd.service
    enabled: yes
