---
- name: Install package
  pacman:
    name:
      - tmux
      - xclip
    update_cache: yes

- name: Install additional aur plugins
  aur:
    name: '{{ item }}'
  become: yes
  become_user: '{{ host.user.wheel.name }}'
  with_items: '{{ host.tmux.plugins.aur }}'

- name: Install additional git plugins
  git:
    repo: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/.tmux/{{ item | regex_search('[^/]+(?=.git)') }}
    depth: 1
  with_items: '{{ host.tmux.plugins.git }}'

- name: Fix permissions
  file:
    path: /home/{{ host.user.wheel.name }}/.tmux
    owner: '{{ host.user.wheel.name }}'
    group: '{{ host.user.wheel.name }}'
    recurse: yes
    mode: 0644

- name: Copy configuration files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: 0644
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .tmux.conf
    - .bashrc.d
