---
- name: Install package
  pacman:
    name:
      - imagemagick
      - libmagick6
    update_cache: yes

- name: Update configuration
  lineinfile:
    path: /etc/ImageMagick-7/policy.xml
    line: '  <policy domain="coder" rights="read | write" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />'
    insertbefore: </policymap>
