---
- name: Refresh pacman cache
  pacman:
    update_cache: yes

- name: Install package
  aur:
    name: skypeforlinux-stable-bin
  become: yes
  become_user: '{{ host.user.wheel.name }}'

- name: Remove autostart
  file:
    state: absent
    path: /home/{{ host.user.wheel.name }}/.config/autostart/skypeforlinux.desktop
