---
- name: Refresh pacman cache
  pacman:
    update_cache: yes

- name: Install package
  aur:
    name: rbenv
  become: yes
  become_user: '{{ host.user.wheel.name }}'

- name: Install plugins
  aur:
    name: ruby-build
  become: yes
  become_user: '{{ host.user.wheel.name }}'

- name: Copy configuration files
  copy:
    src: '{{ item }}'
    dest: /home/{{ host.user.wheel.name }}/
    mode: 0644
    group: '{{ host.user.wheel.name }}'
    owner: '{{ host.user.wheel.name }}'
  with_items:
    - .bashrc.d
    - .gemrc
    - .rspec
    - .rubocop.yml
